In [2]:
import numpy as np


# create array using numpy
# create 1D array

a=np.array([1,2,3])
print(a)
print(type(a))
print(type(a.shape))

[1 2 3]
<class 'numpy.ndarray'>
<class 'tuple'>


In [ ]:

a2=np.array([1,2,3,4,5])
a2.reshape(1,5) # 1 row 5 columns

print(a2)

[1 2 3 4 5]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
np.arange(0,11,2).reshape(6,1)


a = np.eye(3) # get identity matrix
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)


(3, 3)
2
float64
8


In [22]:
# numpy vectorized opreations
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(np.sqrt(a))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1.         1.41421356 1.73205081]
