### NUMPY, vector [[1,2,3],[4,5,6]]
C++ --> numpy based on cpp and c
learn about numpy with chai aur code

In [ ]:
import numpy as np

In [3]:
arr_1d = np.array([1,2,3])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

arr_3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr_3d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
