In [2]:
import numpy as np


# create array using numpy
# create 1D array

a=np.array([1,2,3])
print(a)
print(type(a))
print(type(a.shape))

[1 2 3]
<class 'numpy.ndarray'>
<class 'tuple'>


In [ ]:

a2=np.array([1,2,3,4,5])
a2.reshape(1,5) # 1 row 5 columns

print(a2)

[1 2 3 4 5]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
np.arange(0,11,2).reshape(6,1)


a = np.eye(3) # get identity matrix
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)


(3, 3)
2
float64
8


In [22]:
# numpy vectorized opreations
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(np.sqrt(a))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1.         1.41421356 1.73205081]


In [29]:
# Universal functions
a=np.array([1,2,3])
b=np.array([4,5,6])

# print(np.add(a,b))
# print(np.subtract(a,b))
# print(np.multiply(a,b))
# print(np.divide(a,b))
# print(np.power(a,b))
# print(np.sqrt(a))
# print(np.log(a))
# print(np.exp(a))
# print(np.sin(a))
# print(np.cos(a))
# print(np.tan(a))
# print(np.degrees(a))
# print(np.radians(a))


arr = np.array(
    [
        [1, 2, 3,67],
        [4, 5, 6,65],
        [7, 8, 9,64]
    ])

print(arr)


[[ 1  2  3 67]
 [ 4  5  6 65]
 [ 7  8  9 64]]


In [30]:
arr[0][1]

np.int64(2)

In [ ]:
# statistical concepts -> normalization
a=np.array([1,2,3])
b=np.array([4,5,6])

# print(np.min(a))
# print(np.max(a))
# print(np.min(b))
# print(np.max(b))
# print(np.sum(a))


std = np.std(a)
mean = np.mean(a)
normalized_data = (a - mean) / std

print(normalized_data)

median = np.median(a)
print(median)

variance = np.var(a)
print(variance)

# mode = np.mode(a)
# print(mode)

[-1.22474487  0.          1.22474487]
2.0
0.6666666666666666


AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
data = np.array(
    [
        [1, 2, 3,67],
        [4, 5, 6,65],
        [7, 8, 9,64]
    ]
)

data[(data > 5) & (data < 10)] # all values greater than 5


array([], dtype=int64)